### PR TITLE
 feat: Support thrift uuid type

### LINKED ISSUE #58: Support thrift `uuid` type
The latest thrift version has added support for the `uuid` type.

### PR DESCRIPTION
**Pull request by my-vegetable-has-exploded**
## Motivation

add uuid type for thrift

## Solution

add uuid type ([u8; 16] in rust) for parser 、 resolver and codegen.

close #58

### CODE REVIEW

**Review by PureWhiteWu — DISMISSED** [review]
Thanks for your contribution!
LGTM, PTAL @Millione

**Comment by Millione** [comment]
I remember the bench for unknown use the Message struct, maybe you should fix that either? https://github.com/cloudwego/pilota/blob/main/pilota-build/benches/unknown.rs#L148

**Comment by my-vegetable-has-exploded** [comment]
> I remember the bench for unknown use the Message struct, maybe you should fix that either? https://github.com/cloudwego/pilota/blob/main/pilota-build/benches/unknown.rs#L148

Sorry, I didn't notice it.  Empty uid have been added.

**Review by Millione — APPROVED** [review]

**Comment by my-vegetable-has-exploded** [comment]
thanks

**Pull request merged**
